# fly.toml file generated for still-rain-19 on 2023-02-05T13:13:02+07:00

app = "still-rain-19"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  APP_PORT=8080
  NODE_ENV=".env"
  DB_DRIVER="postgres"
  DB_HOST="db-movie.internal"
  DB_PORT=5432
  DB_NAME="db_movie"
  DB_USERNAME="postgres"
  DB_PASSWORD="iXQXN119Y8XUkjd"
[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
